### ISSUE TITLE
K4NT RTC

### ISSUE THREAD

**Issue by yparitcher** [davidhampgonsalves/life-dashboard#5]
btw, your kindle does support the rtc, it is just a little involved.
see my post on [mobileread](https://www.mobileread.com/forums/showpost.php?p=3812831&postcount=2) for reference. 
This interface can also be accessed from C if desired. 
I made a working screensaver using this: https://github.com/yparitcher/kindle-zmanim

P.S. for easy image displaying I recomend [FBInk](https://github.com/NiLuJe/FBInk)

**Comment by davidhampgonsalves** [comment]
Thanks for this. I did try some methods where I was setting the RTC time during ready to suspend without luck but I'll give your exact method a try next time I flash a new version.

**Comment by pascalw** [comment]
I'm using this method now to trigger the RTC:

```
# trigger RTC
echo 1800 > /sys/devices/platform/mxc_rtc.0/wakeup_enable

# suspend
echo "mem" > /sys/power/state
```

Have you tried this before @yparitcher? It works reliably, but I haven't been able yet to compare battery consumption using this vs `lipc-set-prop -i com.lab126.powerd rtcWakeup`.

**Comment by yparitcher** [comment]
I have not, the advantage of using `lipc` is that it works across device models, the `/sys/` file for the rtc is different for each model and has to be rediscovered.

**Comment by davidhampgonsalves** [comment]
I tried out what you suggested and was able to get the RTC working reliably. Thank you both for taking the time to create this issue. I'm getting ~2 months of run time per charge now.
